workflows:
  ios-release:
    name: iOS Release Build
    integrations:
      app_store_connect: codemagic-key
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        NODE_VERSION: "20.x"
        COCOAPODS_VERSION: "1.15.2"
        BUNDLE_ID: "com.littlestories.app"
        CI: "false"
        DISABLE_ESLINT_PLUGIN: "true"
      groups:
        - Sarastories  # Keep your existing group for other vars
      node: 20
      xcode: latest
    cache:
      cache_paths:
        - ~/.npm
        - node_modules
        - ios/Pods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      # PHASE 1: CLEAN AND SETUP
      - name: Clean Workspace
        script: |
          echo "=== Cleaning Workspace ==="
          rm -rf node_modules ios/Pods ios/App/Pods
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf ios/Pods ios/Podfile.lock
          npm cache clean --force

      # PHASE 2: DEPENDENCY INSTALLATION
      - name: Install Dependencies
        script: |
          set -ex
          echo "=== Installing Node Modules ==="
          npm ci
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
          npx update-browserslist-db@latest

      # PHASE 3: BUILD REACT APP
      - name: Build React App
        script: |
          set -ex
          echo "=== Building React App ==="
          export DISABLE_ESLINT_PLUGIN=true
          npm run build
          if [ ! -d "build" ]; then
            echo "❌ React build failed"
            exit 1
          fi
          echo "✅ React build completed"

      # PHASE 4: CAPACITOR SYNC
      - name: Sync Capacitor for iOS
        script: |
          set -ex
          echo "=== Syncing Capacitor for iOS ==="
          npx cap sync ios
          
          echo "=== Configuring Landscape Orientation ==="
          cd ios/App/App
          PLIST_PATH="Info.plist"
          /usr/libexec/PlistBuddy -c "Delete :UISupportedInterfaceOrientations" "$PLIST_PATH" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Delete :UISupportedInterfaceOrientations~ipad" "$PLIST_PATH" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations array" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations:0 string UIInterfaceOrientationLandscapeLeft" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations:1 string UIInterfaceOrientationLandscapeRight" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations~ipad array" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations~ipad:0 string UIInterfaceOrientationLandscapeLeft" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations~ipad:1 string UIInterfaceOrientationLandscapeRight" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations~ipad:2 string UIInterfaceOrientationPortrait" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations~ipad:3 string UIInterfaceOrientationPortraitUpsideDown" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Delete :UIInterfaceOrientation" "$PLIST_PATH" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :UIInterfaceOrientation string UIInterfaceOrientationLandscapeRight" "$PLIST_PATH"
          echo "✅ Landscape orientation configured"

      # PHASE 5: IOS PROJECT CONFIGURATION
      - name: Configure iOS Project
        script: |
          set -ex
          echo "=== Setting up iOS Platform ==="
          cd ios/App
          cat > Podfile << 'EOF'
          platform :ios, '14.0'
          use_frameworks! :linkage => :dynamic
          install! 'cocoapods', :warn_for_unused_master_specs_repo => false
          target 'App' do
            pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
            pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
            pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
            pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
            pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
            pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
            pod 'CapacitorVoiceRecorder', :path => '../../node_modules/capacitor-voice-recorder'
            pod 'AparajitaCapacitorSecureStorage', :path => '../../node_modules/@aparajita/capacitor-secure-storage'
            pod 'CapacitorBlobWriter', :path => '../../node_modules/capacitor-blob-writer'
          end
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
                config.build_settings['ENABLE_BITCODE'] = 'NO'
                if target.name.start_with?('Capacitor') || target.name.start_with?('Aparajita')
                  config.build_settings['SWIFT_VERSION'] = '5.0'
                  config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
                end
              end
            end
          end
          EOF
          pod repo remove master 2>/dev/null || true
          pod install --repo-update --clean-install
          if [ -d "Pods" ] && [ -d "App.xcworkspace" ]; then
            echo "✅ CocoaPods installation verified"
          else
            echo "❌ CocoaPods installation failed!"
            exit 1
          fi

      # PHASE 6: CREATE XCODE SCHEME
      - name: Create Xcode Scheme
        script: |
          set -ex
          echo "=== Creating missing Xcode scheme ==="
          cd ios/App
          mkdir -p App.xcodeproj/xcshareddata/xcschemes
          cat > App.xcodeproj/xcshareddata/xcschemes/App.xcscheme << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <Scheme LastUpgradeVersion="1500" version="1.7">
            <BuildAction parallelizeBuildables="YES" buildImplicitDependencies="YES">
              <BuildActionEntries>
                <BuildActionEntry buildForTesting="YES" buildForRunning="YES" buildForProfiling="YES" buildForArchiving="YES" buildForAnalyzing="YES">
                  <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="1DF1B9C3257A6D4E00F1B1A6" BuildableName="App.app" BlueprintName="App" ReferencedContainer="container:App.xcodeproj"/>
                </BuildActionEntry>
              </BuildActionEntries>
            </BuildAction>
            <TestAction buildConfiguration="Debug" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.DebuggerFoundation.Launcher.LLDB" shouldUseLaunchSchemeArgsEnv="YES" codeCoverageEnabled="YES">
              <Testables/>
            </TestAction>
            <LaunchAction buildConfiguration="Debug" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.DebuggerFoundation.Launcher.LLDB" launchStyle="0" useCustomWorkingDirectory="NO" ignoresPersistentStateOnLaunch="NO" debugDocumentVersioning="YES" debugServiceExtension="internal" allowLocationSimulation="YES">
              <BuildableProductRunnable runnableDebuggingMode="0">
                <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="1DF1B9C3257A6D4E00F1B1A6" BuildableName="App.app" BlueprintName="App" ReferencedContainer="container:App.xcodeproj"/>
              </BuildableProductRunnable>
            </LaunchAction>
            <ProfileAction buildConfiguration="Release" shouldUseLaunchSchemeArgsEnv="YES" savedToolIdentifier="" useCustomWorkingDirectory="NO" debugDocumentVersioning="YES">
              <BuildableProductRunnable runnableDebuggingMode="0">
                <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="1DF1B9C3257A6D4E00F1B1A6" BuildableName="App.app" BlueprintName="App" ReferencedContainer="container:App.xcodeproj"/>
              </BuildableProductRunnable>
            </ProfileAction>
            <AnalyzeAction buildConfiguration="Debug"/>
            <ArchiveAction buildConfiguration="Release" revealArchiveInOrganizer="YES"/>
          </Scheme>
          EOF
          echo "✅ Xcode scheme created"

    artifacts:
      - ios/App/build/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: codemagic-key 
        submit_to_testflight: true