workflows:
  ios-release:
    name: iOS Release Build
    integrations:
      app_store_connect: codemagic-key
    environment:
      vars:
        APPLE_TEAM_ID: H9A4H444G4
        BUNDLE_ID: com.littlestories.app
      node: 18
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build React app
        script: |
          npm run build
      - name: Sync Capacitor for iOS
        script: |
          npx cap sync ios
      - name: Build iOS archive
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
          -scheme App \
          -configuration Release \
          -archivePath $CM_BUILD_DIR/build/App.xcarchive \
          archive DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
          PROVISIONING_PROFILE_SPECIFIER=$PROVISIONING_PROFILE_UUID \
          CODE_SIGN_STYLE=Manual
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/build/App.xcarchive \
          -exportOptionsPlist ios/App/exportOptions.plist \
          -exportPath $CM_BUILD_DIR/build/ipa
    artifacts:
      - build/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: codemagic-key
        submit_to_testflight: true
